#!/bin/sh -e

cdgopath() {
    mkdir -p "$GOPATH/src/${2%/*}"
    rm -f "$GOPATH/src/$2"
    ln -s "$PWD/$1" "$GOPATH/src/$2"
    cd "$GOPATH/src/$2"
}

out() { printf '\033[1;33m-> \033[m%s\n' "$@"; }

export GO111MODULE=auto

export GOPATH="$PWD"
export PATH="$GOPATH/bin:$PATH"

mkdir -p "$1/usr/bin"

(
    out "Building cli"

    cdgopath docker-ce/components/cli github.com/docker/cli

    BUILDTIME=0 \
    DISABLE_WARN_OUTSIDE_CONTAINER=1 \
    make VERSION="$2-ce"
)

(
    out "Building app cli plugin"

    cdgopath app github.com/docker/app
    make bin/docker-app
)

(
    out "Building daemon"

    cdgopath docker-ce/components/engine github.com/docker/docker
    DOCKER_GITCOMMIT="$2" DOCKER_BUILDTAGS=seccomp VERSION="$2-ce" hack/make.sh binary
)


(
    out "Building docker-proxy"

    cdgopath libnetwork github.com/docker/libnetwork
    CGO_ENABLED=0 go build -ldflags="-linkmode=external" github.com/docker/libnetwork/cmd/proxy
)

(
    out "Building docker-init"

    cdgopath tini github.com/krallin/tini

    export DESTDIR="$1"

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr

    cmake --build build
    cp build/tini-static "$1/usr/bin/docker-init"
)

cp libnetwork/proxy "$1/usr/bin/docker-proxy"

(
    cd docker-ce/components/engine

    cp bundles/binary-daemon/dockerd "$1/usr/bin/dockerd"
)

(
    cd docker-ce/components/cli

    cp build/docker "$1/usr/bin/docker"
)

mkdir -p "$1/etc/sv/docker"

cp run "$1/etc/sv/docker/"
ln -sf /run/runit/supervise.docker "$1/etc/sv/docker/supervise"
