#!/bin/sh -e

patch -p1 < no-bash.patch

mk() {
    make \
        GOLANG=no \
        PREFIX=/usr \
        SBINDIR=/usr/bin \
        LIBDIR=/usr/lib \
        PKGCONFIGDIR=/usr/lib/pkgconfig \
        RAISE_SETFCAP=no \
        INDENT=" " \
        "$@"
}

mk
mk DESTDIR="$1" install
