#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Denable-docs=false \
    -Denable-wayland=false \
    -Denable-xkbregistry=false \
    . output

ninja -C output
ninja -C output install
