#!/bin/sh -e

cat <<EOF

NOTE: The gzip package will be removed from the repos
      and replaced with pigz. Run the following
      to transition to pigz before it is removed.

      kiss b pigz
      kiss i pigz
      kiss a | grep ^pigz | kiss a -
      kiss r gzip

EOF
