#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

cat > config.mak <<EOF
NO_GETTEXT=YesPlease
NO_SVN_TESTS=YesPlease
NO_TCLTK=YesPlease
NO_EXPAT=YesPlease
NO_NSEC=YesPlease
NO_PYTHON=YesPlease
NO_PERL=YesPlease
NO_SYS_POLL_H=1
NO_CROSS_DIRECTORY_HARDLINKS=1
NO_INSTALL_HARDLINKS=1
EOF

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --with-curl \
    ac_cv_snprintf_returns_bogus=no \
    ac_cv_fread_reads_directories=yes

make 
make install

cp -Rf man "$1/usr/share/man"
