#!/bin/sh -e

export DESTDIR="$1"

cd "AppStream-$2"

:>po/meson.build
:>docs/meson.build

patch -p1 < ../no-i18n.patch

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dcompose=false \
    -Dstemming=false \
    -Dgir=false \
    . output

ninja -C output
ninja -C output install
