#!/bin/sh -e

export DESTDIR="$1"

sed -i "/subdir('tests')/d"    meson.build
sed -i "/subdir('examples')/d" meson.build

# Don't clone subprojects we don't even enable
rm -rf subprojects

meson \
    --prefix=/usr \
    -Dgtk_doc=false \
    -Dinstall-tests=false \
    -Dintrospection=disabled \
    . build

ninja -C build
ninja -C build install
