#!/bin/sh -e

printf '\033[1;33mNOTE:\033[m \033[1m%s\n      %s\n      %s\033[m\n' \
    "Please be patient this might take really long, especially during updates." \
    "It might seem to be stuck, but it most probably isn't. The wait can" \
    "be up to 10 minutes."
update-mime-database -V /usr/share/mime
